language: node_js
node_js:
  - lts/*
script:
  - nuxt generate
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  keep-history: true
  edge: true
  on:
    branch: master